["LSOA code"]
old_name = "LSOA code"
Deduced_Data_Type = "str"

["LSOA name"]
old_name = "LSOA name"
Deduced_Data_Type = "str"

["LAD code"]
old_name = "LAD code"
Deduced_Data_Type = "str"

["LAD name"]
old_name = "LAD name"
Deduced_Data_Type = "str"

[Adjust]
old_name = "Adjust"
Deduced_Data_Type = "str" # Although adjust is boolean, it is treated as a string due to the input having a lot of missing values or other values.

[Year]
old_name = "Year"
Deduced_Data_Type = "str" # Although year is numeric, it is treated as a string due to the input possibly being a list of years separated by commas.
